name: Create docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          TAGS="latest,${GITHUB_REF#refs/tags/},$(echo ${GITHUB_REF#refs/tags/} | sed -e 's/\(.*\)\..*/\1/')"
          echo ::set-output name=tags::${TAGS}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
          registry: docker.pkg.github.com
          repository: tohtamysh/php/php
          tags: ${{ steps.prep.outputs.tags }}
